### ISSUE TITLE
lh.white       After opening with Notepad, it is garbled

### ISSUE THREAD

**Issue by tanjia123456** [ThomasYeoLab/CBIG#11]
How to solve this problem？？？

**Comment by rubykong** [comment]
@tanjia123456 You can try with `cat lh.white`

**Comment by tanjia123456** [comment]
This method doesn’t work, do you know any other solutions?

**Comment by tanjia123456** [comment]
> 
> 
> @tanjia123456 You can try with `cat lh.white`

This method doesn’t work, do you know any other solutions?

**Comment by rubykong** [comment]
> > @tanjia123456 You can try with `cat lh.white`
> 
> This method doesn’t work, do you know any other solutions?

@tanjia123456 You can check lh.white from freesurfer and see if you have the same issue or not. If yes, then it might be some problem on your side and I am afraid that there is nothing we can do for you.

**Comment by rubykong** [comment]
The question seems to be irrelevant to CBIG repo. We have suggested the user post this issue in FreeSurfer mailing list.
