### ISSUE TITLE
how to use rh.white to create a mesh?   

### ISSUE THREAD

**Issue by tanjia123456** [ThomasYeoLab/CBIG#12]

**Comment by rubykong** [comment]
@tanjia123456 I am not sure I understand your question. rh.white is a surface template from Freesurfer.

**Comment by tanjia123456** [comment]
> 
> 
> @tanjia123456 I am not sure I understand your question. rh.white is a surface template from Freesurfer.

Yes I know.  rh.white has vertices and triangles, so I want to use these informations to create a mesh. My subject is to segment the cerebral cortex.   so what can i do to create a mesh?  need any other information ?

**Comment by rubykong** [comment]
@tanjia123456 I am very confused. Are you trying to run some code from CBIG repo which requires a mesh structure as input? I am not sure what you meant by "create a mesh". lh.white and rh.white are the surface mesh from freesurfer which should already contain every information. You can load them in Freeview for visualization.

**Comment by tanjia123456** [comment]
> 
> 
> @tanjia123456 I am very confused. Are you trying to run some code from CBIG repo which requires a mesh structure as input? I am not sure what you meant by "create a mesh". lh.white and rh.white are the surface mesh from freesurfer which should already contain every information. You can load them in Freeview for visualization. Maybe you can point me the specific CBIG code you are trying to run?

Hello, this problem has solved.  I would like to ask you a question. After processing with freesurfer (recon all), there are too many vertices, there are more than 130,000. I see a paper that is registered to fsaverage5 (its vertices are only 10000+) to reduce The number of vertices, how is this registration operation realized?

**Comment by rubykong** [comment]
The question seems to be irrelevant to CBIG repo. We have suggested the user post this issue in FreeSurfer mailing list.
