### ISSUE TITLE
template to fsaverage5

### ISSUE THREAD

**Issue by tanjia123456** [ThomasYeoLab/CBIG#13]
hi, I have a question to ask you. I want let rh.white template to fsaverage5.
I know can use mri_surf2surf, but I don't know how to set the parameters（srcsurfval、 src_type 、trg_surf）
**mri_surf2surf --srcsubject bert --srcsurfval thickness --src_type curv --trg_type curv --trgsubject fsaverage5 --trgsurfval white --hemi rh**

so, How to set these parameters for rh.white

**Comment by rubykong** [comment]
@tanjia123456 I am not sure I understand your question. I am not sure which rh.white you are referring to, e.g., rh.white in individual space or rh.white from freesurfer fsaverage5. It seems that your questions are not specific to CBIG repo. I would suggest you write an email to freesurfer user list: https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSupport. I will also close your previous issues, you can post them in freesurfer mailing list too.

**Comment by tanjia123456** [comment]
> I am not sure I understand your question. I am not sure which rh.white you are referring to, e.g., rh.white in individual space or rh.white from freesurfer fsaverage4/5/6/7. It seems that your questions are not specific to CBIG repo. I would suggest you write an email to freesurfer user list: https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSupport. I will also close your previous issues, you can post them in freesurfer mailing list too.

hello, rh.white is obtained by recon all. Because of its too many vertices, it is template to fsaverage5.

**Comment by tanjia123456** [comment]
> > I am not sure I understand your question. I am not sure which rh.white you are referring to, e.g., rh.white in individual space or rh.white from freesurfer fsaverage4/5/6/7. It seems that your questions are not specific to CBIG repo. I would suggest you write an email to freesurfer user list: https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSupport. I will also close your previous issues, you can post them in freesurfer mailing list too.
> 
> hello, rh.white is obtained by recon all. Because of its too many vertices, it is template to fsaverage5.



> > I am not sure I understand your question. I am not sure which rh.white you are referring to, e.g., rh.white in individual space or rh.white from freesurfer fsaverage4/5/6/7. It seems that your questions are not specific to CBIG repo. I would suggest you write an email to freesurfer user list: https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSupport. I will also close your previous issues, you can post them in freesurfer mailing list too.
> 
> hello, rh.white is obtained by recon all. Because of its too many vertices, it is template to fsaverage5.

rh.white is not from fsaverage4/5/6/7

**Comment by rubykong** [comment]
> > > I am not sure I understand your question. I am not sure which rh.white you are referring to, e.g., rh.white in individual space or rh.white from freesurfer fsaverage4/5/6/7. It seems that your questions are not specific to CBIG repo. I would suggest you write an email to freesurfer user list: https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSupport. I will also close your previous issues, you can post them in freesurfer mailing list too.
> > 
> > 
> > hello, rh.white is obtained by recon all. Because of its too many vertices, it is template to fsaverage5.
> 
> > > I am not sure I understand your question. I am not sure which rh.white you are referring to, e.g., rh.white in individual space or rh.white from freesurfer fsaverage4/5/6/7. It seems that your questions are not specific to CBIG repo. I would suggest you write an email to freesurfer user list: https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSupport. I will also close your previous issues, you can post them in freesurfer mailing list too.
> > 
> > 
> > hello, rh.white is obtained by recon all. Because of its too many vertices, it is template to fsaverage5.
> 
> rh.white is not from fsaverage4/5/6/7

I think it's better to post this question in Freesurfer mailing list: https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSupport.

I will close this issue because it's not relevant to CBIG repo.
