### ISSUE TITLE
the freesurfer version when using fsaverage-MNI152 mapping

### ISSUE THREAD

**Issue by younghoo** [ThomasYeoLab/CBIG#14]
hello, I would like to know whether the freesurfer version would influence the results using "fsaverage-MNI152 mapping" tools? Because in the paper (Wu et al., 2018), the freesurfer used is version 4.5.0, which is quite old. And it seems that the fsaverage templates are slightly different across different versions.

**Comment by jadecci** [comment]
Hi! This depends on if you are using the mappings we provided or if you want to use the tool to generate your own mappings. For the former, the FreeSurfer version doesn't matter and you should get the same results using either 4.5 or 6.0. On the other hand, if you run the mapping generation scripts with a different FreeSurfer version, it is likely that the mappings would be different too. Anyway, I would expect the difference to be small; so in general, the FreeSurfer version shouldn't be a problem.
