### ISSUE TITLE
write .annot file error

### ISSUE THREAD

**Issue by tanjia123456** [ThomasYeoLab/CBIG#15]
hello, I updated the label of each vertex through an algorithm. The purpose is to replace the updated labels_id with the labels_id in the .annot file, but the problem now is that I open the .annot file with Notepad and it is garbled. Do you know how to solve it? 
I want to replace the vertex_label in .annot file. If you know ,are you willing to share the source code？

Looking forword to your reply

**Comment by rubykong** [comment]
@tanjia123456 You can use write_annot.m and read_annot.m function from freesufer. You can consult the freesurfer mailing list for more information.  https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSupport
