### ISSUE TITLE
Missing parcels are different between 17 Networks and 7 Networks (Schaefer2018, fsLR 1000 parcels)

### ISSUE THREAD

**Issue by AFurryBear** [ThomasYeoLab/CBIG#17]
### Expected situation
There's two parcels missing in fsLR template. And I've understood this is related to the difference between middlewall in fsaverage and fsLR. I thougt the missing parcels may have different names between 17 Networks and 7 Networks but same IDs.  
### Actual situation
However, the missing parcels are different comparing 17 Networks and 7 Networks. In 17Network, the missing labels are 555 and 908, while in 7Network, the missing labels are 533 and 903. 
![image](https://user-images.githubusercontent.com/22115299/116041071-5c17b300-a69f-11eb-982f-50f0545d0b41.png)
What caused the difference?

**Comment by rubykong** [comment]
@AFurryBear Because the Schaefer_17 and Schaefer_7 have different indices for labels. They are the same parcellation whose labels are ordered based on Yeo 17 networks and Yeo 7 networks. Hope this is clear.
