### ISSUE TITLE
Compatibility of the .lut files with fsleyes

### ISSUE THREAD

**Issue by TalyKo** [ThomasYeoLab/CBIG#18]
Hello, 

I’m trying to add the Schaefer_2018 atlas into FSL, following the instructions in the README file, it seems that the lut file format is not supported with fsleyes (and that the old fslview is now deprecated). 

Is there some way that the atlas can be added?

Thank you in advance,
Taly

**Comment by rubykong** [comment]
@TalyKo I just quickly checked it. It seems like the fsleyes changed a lot of settings compared with fslview. They now require a XML format for loading a new atlas. Check here for how to create a XML file: https://open.win.ox.ac.uk/pages/fsl/fsleyes/fsleyes/userdoc/customising.html#customising-atlases

We will try to provide the XML files asap. You might need to use an older version (5.0.8) of fsl for visualization if you don't want to create the XML files yourself. Will update you once we updated the XML files.

Thanks a lot for reaching us!

Best,
Ruby

**Comment by rubykong** [comment]
@TalyKo We have modified our lut files, will let you know after we released the files.

**Comment by TalyKo** [comment]
Thank you very much!

**Comment by rubykong** [comment]
@TalyKo Here is the updated readme and files:
https://github.com/ThomasYeoLab/CBIG/tree/master/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/Parcellations/MNI
