### ISSUE TITLE
Question: Network Number <-> Network Name

### ISSUE THREAD

**Issue by jdkent** [ThomasYeoLab/CBIG#2]
Thank you so much for making this data available!

### Expected situation
Being easily able to link the network number with the network name

### Actual situation
Difficult to link network number to network name

### Steps to reproduce the issue (optional)
I'm trying to tie the [striatal network atlas](https://surfer.nmr.mgh.harvard.edu/fswiki/StriatumParcellation_Choi2012) with the [schaefer parcellation](https://github.com/ThomasYeoLab/CBIG/blob/master/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/Parcellations/MNI/Schaefer2018_1000Parcels_17Networks_order.txt), but the striatal lists the networks as 1,2,3, etc, whereas the schaefer atlas gives names to the networks without specifying order (e.g. VisCent, VisPeri, etc.). 

I was curious if I'm missing some obvious linker between network1 being the VisCent, VistPeri network or if there was some file that specified this relationship.

Thank you!
James

**Comment by rubykong** [comment]
@jdkent We are trying to release a few scripts to provide the network label with the network name. 
The only problem might be that the network structure could be very different if you are training from scratch on a different dataset. Here are two cases:

#### Use our estimated group priors to estimate individual parcellation
The group atlas will be utilized to initialize the algorithm, therefore, the network order in the individual parcellation will be the same as the group parcellation.
We provided two group priors which are generated by a group atlas estimated by GSP dataset in fsaverage5 space, and a group atlas estimated by HCP dataset in fsLR_32k space. 
I will provide these group atlases with corresponding network labels. 

#### Use your own data to train the model and estimate group priors
If you train on your own data, then your group atlas will be different from ours, the network ordering will also be different. In this way, you will have to run a Hungarian match algorithm to match the networks in your estimated group atlas with our atlases. 
To do that, you can use the following code:

1) If it's fsaverage5, you can directly use the following command to reorder the color table and visualize it:
```
my_par = load('<output_dir>/group/group.mat');
ref_par = load('/Kong2019_MSHBM/examples/results/estimate_group_priors/group/group.mat');
[output, assign, cost, dice_overlap] = CBIG_HungarianClusterMatch([ref_par.lh_labels; ref_par.rh_labels], [my_par.lh_labels; my_par.rh_labels], 1);
colors_old=ref_par.colors(2:end,:);
colors_new=colors_old(assign,:);
colors_new=[[0,0,0];color_new];
CBIG_DrawSurfaceMaps(my_par.lh_labels, my_par.rh_labels, 'fsaverage5', 'inflated',-Inf,Inf,colors_new);
```

2) If your data is in fslr, sorry, I didn't release the HCP group atlas in the current release (will do it asap), so contact me (roo.cone@gmail.com) to get the group atlas file `HCP_40sub_1000iter_17nets_cen_sm4.mat`.
```
my_par = load(fullfile(output_dir,'group','group.mat'));
ref_par = load('HCP_40sub_1000iter_17nets_cen_sm4.mat');
[output, assign, cost, dice_overlap] = CBIG_HungarianClusterMatch([ref_par.lh_labels; ref_par.rh_labels], [my_par.lh_labels; my_par.rh_labels], 1);
colors_old=ref_par.colors(2:end,:);
colors_new=colors_old(assign,:);
CBIG_DrawSurfaceMaps_fslr(my_par.lh_labels, my_par.rh_labels, 'fs_LR_32k', 'inflated',-Inf,Inf,colors_new);
```
I will try to release all above commands and other useful scripts later this month.

**Comment by rubykong** [comment]
@jdkent 

The ROI ordering (and ROI name) of the Schaefer atlases can be found here:
https://github.com/ThomasYeoLab/CBIG/blob/master/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/Parcellations/MNI/Schaefer2018_400Parcels_17Networks_order.txt

Let me know if this is what you are looking for!

**Comment by jdkent** [comment]
Here's a solution I tried to make with the color coding schemes provided, does this look correct?
[network_mapping.txt](https://github.com/ThomasYeoLab/CBIG/files/2823188/network_mapping.txt)

Thanks!

**Comment by rubykong** [comment]
@jdkent Yes. The list you attached is the correct network order of Yeo2011 17-network parcellation (i.e. networks 1 to 17 in https://surfer.nmr.mgh.harvard.edu/fswiki/StriatumParcellation_Choi2012).

**Comment by jdkent** [comment]
Thank you for the confirmation! I'll close this issue.

**Comment by Lnan1615** [comment]
I read a few articles and referenced the Yeo template, but there were 18 networks. Does anybody know the names of these 18 networks?

**Comment by rubykong** [comment]
@Lnan1615 We only have Yeo template with 17networks + medial wall within our lab. I am not sure whether the 18 networks you have seen are the same across studies. One 18-network version I have seen is in "Wang et al., 2015 Parcellating Cortical Functional Networks in Individuals. Nat. Neurosci.". I think you can find the network names in their released code here: http://nmr.mgh.harvard.edu/bid/DownLoad.html

**Comment by Lnan1615** [comment]
Yeah,it is the article that I have seen,but I didn't find the names of regions in their code.
Thank you for replying!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ruby Kong"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月29日(星期三) 下午5:09
收件人:&nbsp;"ThomasYeoLab/CBIG"<CBIG@noreply.github.com&gt;;
抄送:&nbsp;"fouroneninefive"<1059616288@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ThomasYeoLab/CBIG] Question: Network Number <-&gt; Network Name (#2)





 
@Lnan1615 We only have Yeo template with 17networks + medial wall within our lab. I am not sure whether the 18 networks you have seen are the same across studies. One 18-network version I have seen is in "Wang et al., 2015 Parcellating Cortical Functional Networks in Individuals. Nat. Neurosci.". I think you can find the network names in their released code here: http://nmr.mgh.harvard.edu/bid/DownLoad.html
