### ISSUE TITLE
zeros (background) labels in HCP fs_32k space

### ISSUE THREAD

**Issue by iverson333** [ThomasYeoLab/CBIG#22]
The released parcellation labels in HCP surface space of [Yeo](https://github.com/ThomasYeoLab/CBIG/tree/master/stable_projects/brain_parcellation/Yeo2011_fcMRI_clustering/1000subjects_reference/Yeo_JNeurophysiol11_SplitLabels/fs_LR32k) and [Schaefer](https://github.com/ThomasYeoLab/CBIG/tree/master/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/Parcellations/HCP/fslr32k/cifti) (just checked these two) contain a few hundred vertices marked as zeros (background) in the positions of non-medial wall, which should only contain parcellation labels (non-zeros). This is probably due to the misregistration between the volume space and the surface? I tried a nearest neighbor interpolation, but it looks ugly

Do you guys have suggestions of other possible quick fix to this? also this will be definitely better if you guys refine the labels to exclude those zeros. after all it doesn't make sense to have zeros in these positions

zero labeled vertices:
![zeros2](https://user-images.githubusercontent.com/34754010/128790821-88942876-1a76-4846-aa7a-3b2d0f1fca20.png)

nearest neighbor (1-hop neighbor of surface tessellation) interpolated of Yeo2011_7Networks_N1000.dlabel.nii
![interp](https://user-images.githubusercontent.com/34754010/128790538-e2ff5c56-0d96-44e3-9cf4-f1e0c9e44a7b.png)

**Comment by rubykong** [comment]
@iverson333 The schaefer medial wall is not the same as fsLR32k medial wall because Schaefer parcellations were generated in fsaverage6 and then projected to fsLR32k. So the medial wall is a bit different. We won't recommend interplate it, you can just mask the data out for these regions.
