### ISSUE TITLE
atlas - roi

### ISSUE THREAD

**Issue by antoine4ucsd** [ThomasYeoLab/CBIG#24]
Hello
congrats for your impressive work!
I am new with atlas manipulation , I tried various atlas in ggseq  but cannot find one that includes the following region:
- frontal cortex, 
- thalamus, 
- hippocampus, 
- basal ganglia, 
- cerebellum,
- spinal cord

are you aware of such atlas or how I can adapt yours?
my goal is to plot quantitative measures for each of these regions.

thank you

**Comment by rubykong** [comment]
@antoine4ucsd sorry. Which atlas are you referring to? Our lab didn't use ggseq, we mainly use freeview, fsleyes, and wb_view for visualization. You can check here for this toolboxes:
https://surfer.nmr.mgh.harvard.edu/
https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FSLeyes
https://www.humanconnectome.org/software/connectome-workbench
