### ISSUE TITLE
CBIG_ReadNCAvgMesh.m: doesn't check FREESURFER_HOME existence

### ISSUE THREAD

**Issue by 0nu** [ThomasYeoLab/CBIG#27]
When building the freesurfer subjects path `CBIG_ReadNCAvgMesh.m` doesn't check if `$FREESURFER_HOME` exists. If it doesn't, an empty string is returned by `getenv()`, so it should probably be caught by an `if isempty(getenv('FREESURFER_HOME'))`

https://github.com/ThomasYeoLab/CBIG/blob/15f2fa9824c00f1389ed8d074c78fc35b4172207/utilities/matlab/surf/CBIG_ReadNCAvgMesh.m#L24

**Comment by rubykong** [comment]
@0nu we didn't check because all CBIG code can only run if you set up the CBIG environment. Please check this readme:
https://github.com/ThomasYeoLab/CBIG#usage
