### ISSUE TITLE
Error when running CBIG_RNN_ensemble_prediction.sh file

### ISSUE THREAD

**Issue by CrushMzyyy** [ThomasYeoLab/CBIG#30]
Create mask for D2 subjects
Generate test data
train 1667 subjects
test 896 subjects
22 features
Predict using 1st set of pre-trained weights
usage: predict.py [-h] --checkpoint CHECKPOINT --data DATA --prediction
                  PREDICTION
predict.py: error: argument --prediction/-p is required
Predict using 2nd set of pre-trained weights
usage: predict.py [-h] --checkpoint CHECKPOINT --data DATA --prediction
                  PREDICTION
predict.py: error: argument --prediction/-p is required
Predict using 3rd set of pre-trained weights
usage: predict.py [-h] --checkpoint CHECKPOINT --data DATA --prediction
                  PREDICTION
predict.py: error: argument --prediction/-p is required
Predict using 4th set of pre-trained weights
usage: predict.py [-h] --checkpoint CHECKPOINT --data DATA --prediction
                  PREDICTION
predict.py: error: argument --prediction/-p is required

**Comment by mnhng** [comment]
@CrushMzyyy as a temporary fix, you can modify the bash script like so and re-run

```bash
#!/bin/bash
# Written by Minh Nguyen and CBIG under MIT license: https://github.com/ThomasYeoLab/CBIG/blob/master/LICENSE.md
ROOTDIR=`readlink -f $0 | xargs dirname`/../
export PYTHONPATH=$PYTHONPATH:$ROOTDIR

echo Create mask for D2 subjects
python create_mask.py ../data/TADPOLE_D1_D2.csv tadpole_mask.csv

echo Generate test data
python -m cbig.Nguyen2020.gen_com_pickle \
    --mask tadpole_mask.csv \
    --strategy model \
    --spreadsheet ../data/TADPOLE_D1_D2.csv \
    --feat_stat save.seed0/feat_stats.pkl \
    --batch_size 128 \
    --out tadpole_test.pkl

echo Predict using 1st set of pre-trained weights
python -m cbig.Nguyen2020.predict \
    --checkpoint save.seed0 \
    --data tadpole_test.pkl \
    -p prediction0.csv

echo Predict using 2nd set of pre-trained weights
python -m cbig.Nguyen2020.predict \
    --checkpoint save.seed1 \
    --data tadpole_test.pkl \
    -p prediction1.csv

echo Predict using 3rd set of pre-trained weights
python -m cbig.Nguyen2020.predict \
    --checkpoint save.seed2 \
    --data tadpole_test.pkl \
    -p prediction2.csv

echo Predict using 4th set of pre-trained weights
python -m cbig.Nguyen2020.predict \
    --checkpoint save.seed3 \
    --data tadpole_test.pkl \
    -p prediction3.csv

python avg_prediction.py -f prediction{0,1,2,3}.csv -s D4Live
```

**Comment by anlijuncn** [comment]
Hi @CrushMzyyy 

Thanks for your pointing out the typo. We have released the updated version of [Nguyen2020_RNNAD](https://github.com/ThomasYeoLab/CBIG/tree/master/stable_projects/predict_phenotypes/Nguyen2020_RNNAD).
