### ISSUE TITLE
Unrecognized function or variable 'MARS_computeMeshFaceAreas'

### ISSUE THREAD

**Issue by chuanjig** [ThomasYeoLab/CBIG#31]
Dear CBIG group,

I used the 'standalone_scripts_for_MNI_fsaverage_projection' to transform from MNI152 to fsaverage space.

I was able to implement the following function in Matlab:
[lh_proj_data, rh_proj_data] = CBIG_RF_projectMNI2fsaverage('MNI_probMap_ants.central_sulc.nii.gz');

However, when I tried to plot the results using the function below:
CBIG_DrawSurfaceMaps(lh_proj_data, rh_proj_data, 'fsaverage', 'inflated', 0, 1);

I got the error message that: Unrecognized function or variable 'MARS_computeMeshFaceAreas'.
Note that I have downloaded the whole repo and added it in the path of Matlab.

I was able to locate the MARS_computeMeshFaceAreas.c file at CBIG-master/external_packages/SD/SDv1.5.1-svn593/BasicTools but did not find a .m file of it. I'm wondering if you can kindly give some advice on how to resolve the issue?

Thanks in advance!
Chuanji

**Comment by chuanjig** [comment]
I realized it's just that I didn't install correctly, sorry for the post.

**Comment by XiaoqingWu233** [comment]
Hi,Chuanji
Sorry to bother you, but I came across a similar error message: **'Unrecognized function or variable 'MARS_computeMeshFaceAreas'.** when I used the code:
[lh_proj_data, rh_proj_data] = CBIG_RF_projectVol2fsaverage_single('MNI_probMap_ants.central_sulc.nii.gz').

Also, I downloaded the whole repository and added it with subfolders in the path.
I can only find  MARS_computeMeshFaceAreas.c and MARS_computeMeshFaceAreas.mexa64. 
It would be great if you can kindly provide me with a solution.
Thanks so much!

Xiaoqing
