### ISSUE TITLE
Mapping from 17 to 7 and vice versa

### ISSUE THREAD

**Issue by mb3152** [ThomasYeoLab/CBIG#33]
Is there an array you have that can map the ordering of the parcels in the 17 network solution to the 7 network solution, and vice versa? Basically, we have data made in the 17 network ordering, but want to know how it would look in the 7 network ordering.

**Comment by rubykong** [comment]
Hi Max,
It's the Yeo2011_17network or Schaefer parcellation with Yeo17network ordering?

**Comment by audreycluo** [comment]
just following up on Max's question (which he asked on my behalf) -- it's the schaefer parcellation with with Yeo17network ordering

**Comment by mb3152** [comment]
hi @rubykong, any progress on this?

**Comment by rubykong** [comment]
@mb3152 @audreycluo Oh yea. Forgot to reply. We do have the code to get the mapping: 
https://github.com/ThomasYeoLab/CBIG/blob/master/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/Parcellations/Code/CBIG_gwMRF_index_trans_btwn2versions.m

**Comment by rubykong** [comment]
@mb3152 yea you are right. This script can find the mapping between any two Schaefer parcellations with same number of ROIs.

**Comment by rgbayrak** [comment]
It would be fantastic, if this is highlighted in the README file. Could have saved me a lot of time :D
