### ISSUE TITLE
Abbreviations of parcel names - Post vs. PostC

### ISSUE THREAD

**Issue by zhengchencai** [ThomasYeoLab/CBIG#34]
Hi there,

Could you please help to clarify the difference between the parcel abbreviations "Post" and "PostC"? There is no "Post" here https://github.com/ThomasYeoLab/CBIG/tree/master/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/Parcellations, but only "PostC" for post central. This is the same for 17 networks https://github.com/ThomasYeoLab/CBIG/blob/master/stable_projects/brain_parcellation/Yeo2011_fcMRI_clustering/1000subjects_reference/Yeo_JNeurophysiol11_SplitLabels/Yeo2011_17networks_N1000.split_components.glossary.csv. However, in 7 networks https://github.com/ThomasYeoLab/CBIG/blob/master/stable_projects/brain_parcellation/Yeo2011_fcMRI_clustering/1000subjects_reference/Yeo_JNeurophysiol11_SplitLabels/Yeo2011_7networks_N1000.split_components.glossary.csv, we only have "Post" which refers to as "posterior", what do you meant by posterior? Is it same as post central? Thanks a lot. 

Best,
Zhengchen

**Comment by rubykong** [comment]
"Posterior" refers to the spatial location of the ROI. It's a general name, not specifically meant to be post-central.
