### ISSUE TITLE
Schaefer2018 parcellation: difference between gordon prior and gordon_water prior?

### ISSUE THREAD

**Issue by snapfinger** [ThomasYeoLab/CBIG#35]
Hi there, In the example of Schaefer parcellation, the gradient priors (containing fields `border` and `border_matrix`) [are provided](https://github.com/ThomasYeoLab/CBIG/tree/703454dba7b6e0b1cfb97beb449e1593c5170547/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/Code/lib/input) without the need to compute ourselves. However, I'm trying to compute the gradient priors (`border` and `border_matrix`) from my own data. 

I see in the code it says [the paper used option 'gordon'](https://github.com/ThomasYeoLab/CBIG/blob/4cf0a255e071a6c3288f026f021a334c0ec62880/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/Code/lib/CBIG_gwMRF_set_prams.m#L160), but it's not clear to me how this 'gordon' gradient is computed. In the CBIG repo, there's an [implementation of computing gradient](https://github.com/ThomasYeoLab/CBIG/blob/master/utilities/matlab/speedup_gradients/examples/README.md), but because it uses watershed, it seems more likely to be ['gordon_water' option](https://github.com/ThomasYeoLab/CBIG/blob/master/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/Code/lib/CBIG_gwMRF_set_prams.m#L185) in Schaefer parcellation code? However, in [Gordon et al, 2016 paper](https://doi.org/10.1093/cercor/bhu239)'s implementation, there is also a watershed step, so I'm confused about the two. What's the difference between 'gordon' and 'gordon_water'?

**Comment by rubykong** [comment]
Gordon2016 used watershed algorithm in two different steps. If you check my implementation: https://github.com/ThomasYeoLab/CBIG/tree/master/utilities/matlab/speedup_gradients

The readme figure illustrates how the gradient map was generated. The final output can be used as the gradient priors in Schaefer algorithm. However, if you apply the watershed algorithm again on this gradient map, you will get a binarized map. This is the so-called  Gordon2016 parcellation.

To be more specific, the output of my implementation will generate figure 2 in Gordon2016, we call it gradient map. If you apply watershed again on the gradient map, you will get Figure3 in Gordon2016, it's like a binarized version, we call it Gordon2016 parcellation. For Schaefer1018, we use Figure2 in Gordon2016, provided by Gordon2016.

**Comment by snapfinger** [comment]
thanks!
