### ISSUE TITLE
Schaefer parcellation gap between parcels with HCP data

### ISSUE THREAD

**Issue by snapfinger** [ThomasYeoLab/CBIG#38]
Hi there, I successfully ran Schaefer parcellation code on HCP resting-state fMRI data of 500 subjects. However, there are gaps between the parcels (see below) consisting of vertices with seemingly random parcel assignment. I wonder why it is like this and if there's a way to adjust it to the type of no-gap parcels from the [example](https://github.com/ThomasYeoLab/CBIG/tree/master/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/examples) (the bottom image)?

I used the following settings in `CBIG_gwMRF_build_data_and_perform_clustering.m` function

num_left_cluster = 50
num_right_cluster = 50
start_gamma = 5e6;
exponential = 15;
smooth_cost = 1e5;
num_iterations = 100; (gamma_head becomes Inf in the middle of the iterations; I also tried num_iter = 7 such that all gamma_head values are finite in the iterations, but the outputs from the two values are quite similar)
num_runs = 1;

I computed the gradient prior file using the [speedup_gradient code](https://github.com/ThomasYeoLab/CBIG/tree/master/utilities/matlab/speedup_gradients)

HCP 500 subjects:
![Schaefer_HCP_L50R50](https://user-images.githubusercontent.com/13393457/170897704-cc7d4374-8c37-4b25-9553-22a4da54b93c.png)

From example fsaverage6 data:
![Schaefer_fs6_L50R50](https://user-images.githubusercontent.com/13393457/170897707-8443bd7e-6a7e-4e4d-ba37-733a9a28b3d9.png)

**Comment by rubykong** [comment]
@Matilda-Yxx Has helped resolve this issue through email. I will close this issue, for any relevant questions feel free to email xiaoxuan.427@gmail.com
