### ISSUE TITLE
Schaefer parcellation in MNI space

### ISSUE THREAD

**Issue by avaruuser** [ThomasYeoLab/CBIG#39]
Hi all,

First of all, thanks for making this parcellation available to the community!

I tried to load the 1000 parcel parcellation in MNI space using FieldTrip's ft_read_atlas() function. However, I got an error message saying that the data was not in GZIP format. Next, I tried to open the same data with FSLeyes (as per your documentation) and got the same error message. Subsequently, instead of downloading this parcellation from your repository, I also tried fetching the data with the NILearn python package using nilearn.datasets.fetch_atlas_schaefer_2018(). The data fetched with NILearn indeed seems to work with FSLeyes and FieldTrip. Am I doing something wrong or is there an issue with the MNI parcellation?

Once I got the data (fetched with NILearn) loaded using FieldTrip, I did some basic checks and it appears that the origin (0,0,0) lies outside of the brain. As far as I understand, the origin of the MNI spaces are usually set to the anterior commissure.

Could you help me to figure out how to properly load the MNI space parcellation?

**Comment by rubykong** [comment]
Which file were you trying to load through FSLeyes? I tried Schaefer2018_1000Parcels_7Networks_order_FSLMNI152_2mm and it loaded without error. I am using FSLeyes from FSL5.0.10

**Comment by avaruuser** [comment]
Hey @rubykong, sorry, this was an error from my side. The data got corrupted with my download script.
