### ISSUE TITLE
Multi-echo CBIG2016 Preprocessing

### ISSUE THREAD

**Issue by peter3200** [ThomasYeoLab/CBIG#42]
### Expected situation
When the bold/001/ME_intermediate folder from Tedana is not created, an error is thrown indicating that the folder does not exist and there was an issue with Tedana. This would be very helpful for troubleshooting errors and indicating whether or not Tedana is setup correctly.

### Actual situation
The logfile (CBIG_preproc_multiecho_denoise.log) indicates that Tedana finished even though no ME_intermediate folder was created:

=====================combine echos and perform multi-echo ICA using tedana ======================
tedana -d sub-35793_bld001_e1_rest_skip4_mc.nii.gz sub-35793_bld001_e2_rest_skip4_mc.nii.gz sub-35793_bld001_e3_rest_skip4_mc.nii.gz -e 12.4 34.28 56.16 --out-dir /CBIG2016_preproc_FS6/sub-35793/sub-35793/bold/001/ME_intermediate
====================== Multi-echo ICA finished. ======================

Thank you for creating this wonderful resource!

**Comment by rubykong** [comment]
@xiumingzhang Can you help look into this?

**Comment by ShaoshiZ** [comment]
If I recall correctly, this problem occurred because CBIG_py3 was not activated when running the multiecho step.
