### ISSUE TITLE
CBIG2016 Preproc - Spatial Distortion Correction

### ISSUE THREAD

**Issue by peter3200** [ThomasYeoLab/CBIG#45]
### Expected situation
I attempted to run spatial distortion correction with fieldmaps that each have more than one volume.

### Actual situation
The pipeline implicitly assumes that fieldmaps only have one volume, so the datain.txt file is generated with two lines (reflecting a total of two volumes in the AP_PA.nii.gz file). This creates an error when there are more than two volumes in the AP_PA.nii.gz file:

Topup: msg=topup_clp::topup_clp: Mismatch between /fslgroup/grp_proc/compute/Nielson_analysis/CBIG2016_preproc_FS6/sub-23638/sub-23638/bold/sdc/AP_PA.nii.gz and /fslgroup/grp_proc/compute/Nielson_analysis/CBIG2016_preproc_FS6/sub-23638/sub-23638/bold/sdc/datain.txt

### Steps to reproduce the issue (optional)
This error can be reproduced using the multi-echo masking test dataset on Openneuro: https://openneuro.org/datasets/ds002156/versions/2.0.0 (ds002156).

**Comment by ShaoshiZ** [comment]
Hi,

You're right that this script can only take in 2 single-volume AP and PA fieldmaps. In the case of multiple volumes, currently we adopt a similar method to this [script](https://git.fmrib.ox.ac.uk/falmagro/UK_biobank_pipeline_v_1/-/blob/master/bb_structural_pipeline/bb_choose_bestB0) to pick a pair of single-volume AP and PA fieldmaps. From our experience of preprocessing UKBiobank data, we didn't notice any big difference in terms of registration quality between functional and structural images across different possible combinations of AP and PA fieldmap volumes.

Shaoshi
