### ISSUE TITLE
Error in CBIG_VonmisesSeriesClustering_fix_bessel_randnum_bsxfun

### ISSUE THREAD

**Issue by QunjunLIANG** [ThomasYeoLab/CBIG#5]
In step1: CBIG_MSHBM_generate_ini_params

An error occurred:
In an assignment  A(I) = B, the number of elements in B and I
must be the same.

When calling function CBIG_VonmisesSeriesClustering_fix_bessel_randnum_bsxfun
 (line 171: rh_s(l2) = s(length(l1)+1:end);)

My MATLAB version is R2014a in Linux and the data are in HCP format (dtseries.nii). 
I ran the function following the user guide and the first 2 scripts in step1 had already been finished without error.

How should I fix this error?

**Comment by rubykong** [comment]
@QunjunLIANG Thanks for spotting this!

This error may happen if you have a vertex which has zero correlation with all the ROIs across all the subjects and all the sessions. 

We have fixed the code to handle this issue. Can you try to update your repo with the latest version and try it again? Please let us know if the error still occurs.

**Comment by QunjunLIANG** [comment]
Thanks for your prompt reply! I have already update the repo to the latest version and the error mentioned above never shows up.

But there comes another error in the same pipeline:
Error using CBIG_DrawSurfaceMaps (line 83)
Not handling 32492 vertices
Error in CBIG_MSHBM_generate_ini_params (line 72)
CBIG_DrawSurfaceMaps(lh_labels, rh_labels, 'fsaverage5', 'inflated');

It seems the input metric of fs_32k is too large to the function availability.
How should I get over it? 

By the way, I have a question in CBIG_MSHBM_avg_profiles.m 
Seems the code can not identify split_flag files generated by CBIG_MSHBM_generate_profiles.m
So how should I generate the average profiles using split_flag files? 
Rename and put them in the correct path manually, maybe?

**Comment by QunjunLIANG** [comment]
After I changed the function `CBIG_DrawSurfaceMaps` to `CBIG_DrawSurfaceMaps_fslr`, the pipeline was done without error.

**Comment by rubykong** [comment]
@QunjunLIANG We don't recommend users to use split flags when average across profiles. Instead, you might also need to compute profiles with 1 session without split flag.

Thanks a lot for catching the bug of visualization! I will fix it in the next release.

**Comment by rubykong** [comment]
@QunjunLIANG I have replied your email, but your email address can be not be delivered. Can you send me another email address?
