### ISSUE TITLE
Schaefer2018 parcellation in individual surface space : no sphere.reg file

### ISSUE THREAD

**Issue by vferat** [ThomasYeoLab/CBIG#6]
I'm trying to follow  [this example](https://github.com/ThomasYeoLab/CBIG/tree/master/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/Parcellations/project_to_individual) in order to parcellate an individual brain. However whenI try to run mri_surf2, it raises an error saying it does not find the lh.sphere.reg ( not provided in the repo)
Do I have to manually create this file ? If yes can you explain me the different steps to achieve that ?

### Actual situation
mri_surf2surf: could not read surface **...**/fsaverage6/surf/lh.sphere.reg
No such file or directory
Return code: 255

### Steps to reproduce the issue (optional)
Run the following command:
```
mri_surf2surf 
 --hemi lh
 --tval **...**/PT02/lh.Schaefer2018_1000Parcels_17Networks_order.annot
--sval-annot **...**/fsaverage6/label/lh.Schaefer2018_1000Parcels_17Networks_order.annot --srcsubject fsaverage6
--trgsubject PT02
```

Thanks for all yur work,
Victor

**Comment by rubykong** [comment]
@vferat This happens if your `fsaverage6` and `PT02` are not in the `$SUBEJCTS_DIR`.
You need to first create a symbolic link for `fsaverage6` in your `$SUBJECTS_DIR` (it should be the folder contain `PT02`)  
```
ln -s /apps/arch/Linux_x86_64/freesurfer/5.3.0/subjects/fsaverage6 
```

**Comment by vferat** [comment]
Hey @rubykong , thanks for you answer
Both subject (PT02 and fsaverage) are in the same folder. I only downloaded the fsaverage6 folder available in this repo, but there is no lh.sphere or lh.sphere.reg here. 
Do I have to download the full fsaverage6 folder  ([ this one](ftp://surfer.nmr.mgh.harvard.edu/pub/data/Yeo_JNeurophysiol11_FreeSurfer.zip) ? ) and overwrite files with the ones of this repo ?

**Comment by rubykong** [comment]
@vferat You might need to replace this `fsaverage6` folder with the one from freesurfer: freesurfer/5.3.0/subjects/fsaverage6

**Comment by vferat** [comment]
Perfect @rubykong  it's working ! Thanks a lot. 👍 


Last question : To use the` surf2surf` with the `fsaverage6 `provided , does my subject need to be registered to the `average.curvature.filled.buckner40.tif`  default template ?

**Comment by rubykong** [comment]
@vferat I am actually not super sure. We normally just run the standard recon-all pipeline. I think you can check with the freesurfer mailing list. You can also load the individual surface mesh (e.g. PT02/surf/lh.inflated) and the mri_surf2surf output (i.e. PT02/lh.Schaefer2018_1000Parcels_17Networks_order.annot) in freeview to visually check if it looks okay.

**Comment by vferat** [comment]
I ran parcellation using both `mris_ca_label`(with the .gcs files)  and `surf2surf`  for the100 labels 7 networks and fond a  2% difference in voxel labels between both files, so I assume the method works correctly. If I found more information, I'll keep you inform. 
Thanks again for your help
