### ISSUE TITLE
fsaverage to MNI projection

### ISSUE THREAD

**Issue by MRC-CBSU** [ThomasYeoLab/CBIG#8]
I've downloaded the standalone scripts for MNI to fsaverage projection. Can these be used to do the reverse, i.e., project data from fsaverage to MNI space?

Thanks, 
Marta

**Comment by jadecci** [comment]
Hi! Right now there isn't a standalone script for fsaverage to MNI projection. 

To project data from fsaverage to MNI space, you would need to download the CBIG repository. Then use the script `CBIG_RF_projectfsaverage2Vol_single.m` or `CBIG_RF_projectfsaverage2Vol_batch.sh` in the `stable_projects/registration/Wu2017_RegistrationFusion/bin/scripts_final_proj` directory.

**Comment by mitchellxh** [comment]
Just to clarify, after completing my recon-all of a subject what are my lh* and rh* inputs to the .sh script? I see the following:

	-l <input_list>  absolute path to file containing input data file names. Each line in the file should contain full path to one file. Note that the inputs should be in .mat format, containing two variables 'lh_label' and 'rh_label', corresponding to the input data in left and right hemispheres respectively.

I'm not entirely sure what .mat files I should be directing to in my input list. I think I'm missing a step between recon-all and running this script creating the .mat files.

**Comment by jadecci** [comment]
You can create the .mat file by putting your data in left and right hemisphere in the variables 'lh_label' and 'rh_label' respectively. Each of the variables should be a vector of length 163842, for example, for data on the fsaverage surface. 

May I know which data from recon-all do you want to project to MNI space?

**Comment by Reine0017** [comment]
> Hi! Right now there isn't a standalone script for fsaverage to MNI projection.
> 
> To project data from fsaverage to MNI space, you would need to download the CBIG repository. Then use the script `CBIG_RF_projectfsaverage2Vol_single.m` or `CBIG_RF_projectfsaverage2Vol_batch.sh` in the `stable_projects/registration/Wu2017_RegistrationFusion/bin/scripts_final_proj` directory.

Really sorry to trouble you but may I ask for my detailed instructions on how to do this? Or some documentation you'd be able to refer me to?

**Comment by jadecci** [comment]
All the relevant commands that you can use should be on [this page](https://github.com/ThomasYeoLab/CBIG/tree/master/stable_projects/registration/Wu2017_RegistrationFusion/bin/scripts_final_proj).

Is there a specific function/script that you need help with?

**Comment by Reine0017** [comment]
Hey @jadecci! Thanks so much for replying me and sending that link! I'll look into it :)
